# Generated by Django 4.2.29 on 2026-03-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('delivery_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('open_interest', models.BigIntegerField(blank=True, null=True)),
                ('previous_open_interest', models.BigIntegerField(blank=True, null=True)),
                ('oi_change', models.BigIntegerField(blank=True, null=True)),
                ('price_change_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('volume_spike_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['-date', 'symbol'],
                'unique_together': {('symbol', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IntradaySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold')], max_length=4)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.stock')),
            ],
            options={
                'db_table': 'intraday_signals',
                'ordering': ['-date', '-confidence_score'],
                'unique_together': {('stock', 'date', 'signal_type')},
            },
        ),
    ]
