# Generated by Django 4.2.29 on 2026-03-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('signal_type', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HIT_TARGET', 'Hit Target'), ('HIT_SL', 'Hit SL'), ('EXPIRED', 'Expired')], db_index=True, default='ACTIVE', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'signal_history',
                'ordering': ['-generated_at'],
            },
        ),
    ]
