# Generated by Django 4.2.29 on 2026-03-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_signalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('change_type', models.CharField(choices=[('SIGNAL_FLIP', 'Signal Flip'), ('EXPIRY_ROLL', 'Expiry Roll'), ('ENTRY_UPDATED', 'Entry Updated'), ('NEW_SIGNAL', 'New Signal'), ('SIGNAL_REMOVED', 'Signal Removed')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'signal_change_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
