# Generated by Django 4.2.29 on 2026-03-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_signalchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalchangelog',
            name='category',
            field=models.CharField(default='intraday', max_length=20),
        ),
    ]
