# Generated by Django 4.2.29 on 2026-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_signalchangelog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='category',
            field=models.CharField(db_index=True, default='intraday', max_length=20),
        ),
    ]
