# Generated by Django 4.2.29 on 2026-03-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalhistory',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('HIT_TARGET', 'Hit Target'), ('HIT_SL', 'Hit SL'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
