# Generated by Django 4.2.29 on 2026-04-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_indexconstituent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='signalhistory',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE'])), fields=('symbol', 'category', 'status'), name='unique_live_signal'),
        ),
    ]
