# Generated by Django 4.2.29 on 2026-04-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_signalhistory_unique_live_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='option_type',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='strike_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
