# Generated by Django 4.2.29 on 2026-04-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_signalhistory_option_type_signalhistory_strike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='option_expiry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='premium_cmp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
