# Generated by Django 4.2.29 on 2026-04-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_signalhistory_option_expiry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('spot_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pcr', models.DecimalField(decimal_places=4, max_digits=8)),
                ('max_pain', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_ce_oi', models.BigIntegerField(default=0)),
                ('total_pe_oi', models.BigIntegerField(default=0)),
                ('chain_data_json', models.JSONField(blank=True, default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'option_chains',
                'ordering': ['-timestamp'],
            },
        ),
    ]
