# Generated by Django 4.2.29 on 2026-04-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_optionchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
