# Generated by Django 4.2.29 on 2026-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_signalhistory_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalhistory',
            name='telegram_active_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='telegram_exit_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalhistory',
            name='telegram_signal_sent',
            field=models.BooleanField(default=False),
        ),
    ]
