# Generated by Django 4.2.29 on 2026-05-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_telegram_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(db_index=True, default='NSE', max_length=20)),
                ('holiday_date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'market_holidays',
                'ordering': ['holiday_date'],
            },
        ),
    ]
