# Generated by Django 4.2.29 on 2026-05-26 07:00

from django.db import migrations
from datetime import date

def seed_nse_holidays(apps, schema_editor):
    MarketHoliday = apps.get_model('stocks', 'MarketHoliday')
    
    holidays = [
        # ── 2025 ──
        (date(2025, 2, 26), "Mahashivratri"),
        (date(2025, 3, 14), "Holi"),
        (date(2025, 3, 31), "Ram Navami"),
        (date(2025, 4, 10), "Mahavir Jayanti"),
        (date(2025, 4, 14), "Dr. Baba Saheb Ambedkar Jayanti"),
        (date(2025, 4, 18), "Good Friday"),
        (date(2025, 5, 1), "Maharashtra Day"),
        (date(2025, 8, 15), "Independence Day"),
        (date(2025, 8, 27), "Ganesh Chaturthi"),
        (date(2025, 10, 2), "Mahatma Gandhi Jayanti"),
        (date(2025, 10, 21), "Diwali Laxmi Puja"),
        (date(2025, 10, 22), "Diwali Balipratipada"),
        (date(2025, 11, 5), "Gurunanak Jayanti"),
        (date(2025, 12, 25), "Christmas"),
        # ── 2026 ──
        (date(2026, 1, 26), "Republic Day"),
        (date(2026, 2, 17), "Mahashivratri"),
        (date(2026, 3, 4), "Holi"),
        (date(2026, 3, 20), "Good Friday"),
        (date(2026, 3, 26), "Ramzan Id (Id-Ul-Fitr)"),
        (date(2026, 3, 31), "Ram Navami"),
        (date(2026, 4, 3), "Good Friday / Mahavir Jayanti"),
        (date(2026, 4, 14), "Dr. Baba Saheb Ambedkar Jayanti"),
        (date(2026, 5, 1), "Maharashtra Day"),
        (date(2026, 6, 7), "Bakri Id"),
        (date(2026, 7, 7), "Moharram"),
        (date(2026, 8, 15), "Independence Day"),
        (date(2026, 8, 17), "Parsi New Year"),
        (date(2026, 9, 4), "Id-E-Milad"),
        (date(2026, 10, 2), "Mahatma Gandhi Jayanti"),
        (date(2026, 10, 12), "Dussehra"),
        (date(2026, 11, 9), "Diwali Balipratipada"),
        (date(2026, 11, 10), "Gurunanak Jayanti"),
        (date(2026, 11, 25), "Guru Tegh Bahadur Martyrdom Day"),
        (date(2026, 12, 25), "Christmas"),
        # ── 2027 (Provisional/Fixed National Holidays) ──
        (date(2027, 1, 26), "Republic Day"),
        (date(2027, 4, 14), "Dr. Baba Saheb Ambedkar Jayanti"),
        (date(2027, 5, 1), "Maharashtra Day"),
        (date(2027, 8, 15), "Independence Day"),
        (date(2027, 10, 2), "Mahatma Gandhi Jayanti"),
        (date(2027, 12, 25), "Christmas"),
    ]
    
    for h_date, name in holidays:
        MarketHoliday.objects.update_or_create(
            holiday_date=h_date,
            defaults={
                "market": "NSE",
                "name": name,
                "is_active": True
            }
        )

def remove_nse_holidays(apps, schema_editor):
    MarketHoliday = apps.get_model('stocks', 'MarketHoliday')
    MarketHoliday.objects.filter(market="NSE").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_marketholiday'),
    ]

    operations = [
        migrations.RunPython(seed_nse_holidays, remove_nse_holidays),
    ]
