# Generated by Django 4.2.29 on 2026-06-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_seed_nse_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalhistory',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='signalhistory',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
