# Generated by Django 4.2.29 on 2026-07-15 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_make_stop_loss_target_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('HIT_TARGET', 'Hit Target'), ('HIT_SL', 'Hit SL'), ('CLOSED', 'Position Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('vol_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('setup', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'db_table': 'short_term_signals',
                'ordering': ['-generated_at'],
            },
        ),
    ]
