# Generated by Django 4.2.29 on 2026-07-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_shorttermsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(db_index=True)),
                ('ai_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('trend_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('momentum_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('volume_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('sector_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fundamental_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('holding_days', models.IntegerField(default=30)),
                ('expiry_days', models.IntegerField(default=30)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='stocks.stock')),
            ],
            options={
                'db_table': 'trade_scanner',
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('target3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('HOLDING', 'Holding'), ('TARGET1', 'Target 1 Reached'), ('TARGET2', 'Target 2 Reached'), ('TRAILING', 'Trailing Stop Active'), ('EXITED', 'Exited Position'), ('STOPLOSS', 'Hit Stop Loss'), ('EXPIRED', 'Expired Setup'), ('CANCELLED', 'Cancelled Setup')], db_index=True, default='PENDING', max_length=20)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('activated_date', models.DateField(blank=True, null=True)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('holding_days', models.IntegerField(default=0)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='stocks.stock')),
            ],
            options={
                'db_table': 'trades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='stocks.trade')),
            ],
            options={
                'db_table': 'telegram_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='StockDailyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('delivery_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('ema20', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ema50', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ema200', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rsi14', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('adx14', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('atr14', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_52week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_52week', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sector_return', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('nifty_return', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_data', to='stocks.stock')),
            ],
            options={
                'db_table': 'stock_daily_data',
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
