# Generated by Django 4.2.29 on 2026-07-17 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_tradescanner_trade_telegramlog_stockdailydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermsignal',
            name='cooldown_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp until when scanner must ignore this symbol', null=True, verbose_name='Cooldown Until'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='exit_reason',
            field=models.CharField(blank=True, help_text='Detailed reason for trade exit', max_length=100, verbose_name='Exit Reason'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='highest_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Peak realized or unrealized profit reached', max_digits=12, verbose_name='Highest Profit'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='max_drawdown',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum drawdown percentage or value experienced', max_digits=12, verbose_name='Max Drawdown'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='review_required',
            field=models.BooleanField(default=False, help_text='Flag indicating trade requires manual assessment', verbose_name='Review Required'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='target2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Second target price level', max_digits=12, null=True, verbose_name='Target 2'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='target3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Third final target price level', max_digits=12, null=True, verbose_name='Target 3'),
        ),
        migrations.AddField(
            model_name='telegramlog',
            name='delivery_status',
            field=models.CharField(db_index=True, default='PENDING', help_text='Real-time delivery progress of Telegram alert', max_length=20, verbose_name='Delivery Status'),
        ),
        migrations.AddField(
            model_name='telegramlog',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, help_text='Dynamic event slug matching strategy lifecycles', max_length=50, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='telegramlog',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of delivery retries attempted', verbose_name='Retry Count'),
        ),
        migrations.AddField(
            model_name='telegramlog',
            name='short_term_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='stocks.shorttermsignal'),
        ),
        migrations.AlterField(
            model_name='shorttermsignal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('TARGET1', 'Target 1'), ('TARGET2', 'Target 2'), ('HIT_TARGET', 'Hit Target'), ('HIT_SL', 'Hit SL'), ('TRAILING_EXIT', 'Trailing Exit'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REVIEW_REQUIRED', 'Review Required'), ('CLOSED', 'Position Closed'), ('ARCHIVED', 'Archived'), ('COOLDOWN', 'Cooldown')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramlog',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramlog',
            name='trade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='stocks.trade'),
        ),
        migrations.AlterField(
            model_name='telegramlog',
            name='type',
            field=models.CharField(help_text='Alert type indicator', max_length=50, verbose_name='Alert Type'),
        ),
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(db_index=True, help_text='Previous lifecycle state', max_length=50, verbose_name='Old Status')),
                ('new_status', models.CharField(db_index=True, help_text='New transitioned lifecycle state', max_length=50, verbose_name='New Status')),
                ('price', models.DecimalField(decimal_places=2, help_text='Execution price during status change', max_digits=12, verbose_name='Price')),
                ('reason', models.TextField(blank=True, help_text='Detailed context or trigger event details', verbose_name='Reason')),
                ('triggered_by', models.CharField(default='SYSTEM', help_text='User or automation trigger', max_length=50, verbose_name='Triggered By')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Audit log creation time', verbose_name='Timestamp')),
                ('trade', models.ForeignKey(help_text='ForeignKey pointing to ShortTermSignal', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='stocks.shorttermsignal', verbose_name='Swing Signal')),
            ],
            options={
                'db_table': 'trade_history',
                'ordering': ['-timestamp'],
            },
        ),
    ]
