# Generated by Django 4.2.29 on 2026-07-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_shorttermsignal_cooldown_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermsignal',
            name='expected_holding_days',
            field=models.IntegerField(blank=True, help_text='ATR-based estimated holding period set at scan time; EOD evaluation force-exits at market price once this elapses without a target/SL hit', null=True, verbose_name='Expected Holding Days'),
        ),
        migrations.AlterField(
            model_name='shorttermsignal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('TARGET1', 'Target 1'), ('TARGET2', 'Target 2'), ('HIT_TARGET', 'Hit Target'), ('HIT_SL', 'Hit SL'), ('TRAILING_EXIT', 'Trailing Exit'), ('TIME_STOP', 'Time Stop Exit'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('REVIEW_REQUIRED', 'Review Required'), ('CLOSED', 'Position Closed'), ('ARCHIVED', 'Archived'), ('COOLDOWN', 'Cooldown')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
