# Generated by Django 4.2.29 on 2026-07-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0024_shorttermsignal_expected_holding_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermsignal',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Composite AI score (0-100) computed by the daily scanner at scan time', max_digits=5, null=True, verbose_name='AI Score'),
        ),
    ]
