# Generated by Django 4.2.29 on 2026-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0025_shorttermsignal_ai_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowwHistorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='Snapshot Date')),
                ('option_selling_picks', models.JSONField(default=list, help_text='Locked CE/PE picks with entry/current premium and P&L at snapshot time', verbose_name='Option Selling Picks')),
                ('option_selling_total_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Option Selling Total P&L')),
                ('swing_picks', models.JSONField(default=list, help_text='Passing swing setups (symbol, ai_score, entry, SL, targets) at snapshot time', verbose_name='Swing Stock Picks')),
                ('nifty_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Nifty 50 Snapshot')),
                ('captured_at', models.DateTimeField(auto_now=True, help_text='Updated each time the snapshot is (re)saved for this date', verbose_name='Last Captured At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='First Created At')),
            ],
            options={
                'db_table': 'groww_history_snapshot',
                'ordering': ['-date'],
            },
        ),
    ]
