# Generated by Django 4.2.30 on 2026-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0027_delete_growwhistorysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('interval', models.CharField(db_index=True, max_length=20)),
                ('ts', models.DateTimeField(db_index=True)),
                ('open', models.DecimalField(decimal_places=2, max_digits=14)),
                ('high', models.DecimalField(decimal_places=2, max_digits=14)),
                ('low', models.DecimalField(decimal_places=2, max_digits=14)),
                ('close', models.DecimalField(decimal_places=2, max_digits=14)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'candle_bars',
                'ordering': ['symbol', 'interval', 'ts'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'ts'], name='candle_lookup_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='candlebar',
            constraint=models.UniqueConstraint(fields=('symbol', 'exchange', 'interval', 'ts'), name='unique_candle_bar'),
        ),
    ]
