# Generated by Django 4.2.30 on 2026-07-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0028_candlebar_candlebar_unique_candle_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('ex_date', models.DateField(db_index=True)),
                ('action_type', models.CharField(choices=[('SPLIT', 'Stock Split'), ('BONUS', 'Bonus Issue'), ('DIVIDEND', 'Dividend'), ('RIGHTS', 'Rights Issue'), ('DEMERGER', 'Demerger')], max_length=20)),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('raw_description', models.TextField(blank=True)),
                ('source', models.CharField(default='nse', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_actions',
                'ordering': ['-ex_date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='EarningsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('event_date', models.DateField(db_index=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(default='nse', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'earnings_events',
                'ordering': ['-event_date', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='PromoterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('group_name', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='curated', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promoter_groups',
                'ordering': ['group_name', 'symbol'],
            },
        ),
        migrations.CreateModel(
            name='TradeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(choices=[('intraday', 'Intraday'), ('swing', 'Swing'), ('long_term', 'Long Term')], db_index=True, max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('setup_family', models.CharField(blank=True, db_index=True, max_length=40)),
                ('direction', models.CharField(default='BUY', max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('exit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('r_multiple', models.DecimalField(blank=True, db_index=True, decimal_places=3, max_digits=8, null=True)),
                ('pnl_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pnl_inr', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('mae_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mfe_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('exit_reason', models.CharField(db_index=True, max_length=40)),
                ('regime_snapshot', models.JSONField(blank=True, default=dict)),
                ('rank_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rank_factors', models.JSONField(blank=True, default=dict)),
                ('holding_days', models.IntegerField(default=0)),
                ('holding_minutes', models.IntegerField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trade_outcomes',
                'ordering': ['-closed_at'],
            },
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='cost_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Round-trip cost assumption at generation', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='entry_valid_until',
            field=models.DateField(blank=True, help_text='Last session this PENDING entry may activate', null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='qty',
            field=models.IntegerField(blank=True, help_text='Risk-parity share count computed at generation', null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='rank_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Per-factor breakdown behind rank_score, for attribution'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='rank_score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, help_text='Cross-sectional 0-100 rank from shared/ranking.py', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='regime_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='RegimeState captured when the signal was generated'),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='rupee_risk',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rupee risk at entry (qty x per-share risk)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='setup_family',
            field=models.CharField(blank=True, db_index=True, help_text='MOMENTUM | PULLBACK', max_length=20),
        ),
        migrations.AddField(
            model_name='shorttermsignal',
            name='target_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Target move %, for EV attribution', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shorttermsignal',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED — superseded by rank_score. Never written by swing V2.', max_digits=5, null=True, verbose_name='AI Score'),
        ),
        migrations.AddIndex(
            model_name='shorttermsignal',
            index=models.Index(fields=['status', '-generated_at'], name='sts_status_gen_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeoutcome',
            index=models.Index(fields=['engine', 'setup_family', '-closed_at'], name='outcome_engine_setup_idx'),
        ),
        migrations.AddConstraint(
            model_name='earningsevent',
            constraint=models.UniqueConstraint(fields=('symbol', 'event_date'), name='unique_earnings_event'),
        ),
        migrations.AddConstraint(
            model_name='corporateaction',
            constraint=models.UniqueConstraint(fields=('symbol', 'ex_date', 'action_type'), name='unique_corporate_action'),
        ),
    ]
