# Generated by Django 4.2.30 on 2026-07-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0029_corporateaction_earningsevent_promotergroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(db_index=True, max_length=20)),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('direction', models.CharField(max_length=8)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=14)),
                ('stop', models.DecimalField(decimal_places=2, max_digits=14)),
                ('target', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rank_score', models.FloatField(blank=True, null=True)),
                ('rank_factors', models.JSONField(blank=True, default=dict)),
                ('regime_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'signal_candidates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('exchange', models.CharField(default='NSE', max_length=10)),
                ('interval', models.CharField(db_index=True, max_length=20)),
                ('since_ts', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('requested_by', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'download_requests',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='download_request_drain_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='downloadrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'IN_PROGRESS'])), fields=('symbol', 'exchange', 'interval'), name='unique_pending_download_request'),
        ),
    ]
