# Generated by hand 2026-07-28 (not via `manage.py makemigrations` — running any
# management command locally triggers AppConfig.ready(), which logs into the live
# Angel One session as a side effect). Matches the field exactly as added to
# stocks/models.py's TelegramLog.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0030_signalcandidate_downloadrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlog',
            name='chat_id',
            field=models.CharField(
                blank=True,
                default='',
                max_length=32,
                verbose_name='Target Chat ID',
                help_text=(
                    "Added 2026-07-28: queue_telegram_message()'s chat_id override used to be "
                    "computed and immediately discarded — process_telegram_queue() hardcoded "
                    "every queued message to the short-term chat regardless. Blank means "
                    "'use the short-term chat', for backward compatibility with rows queued "
                    "before this field existed."
                ),
            ),
        ),
    ]
