# Generated by hand 2026-07-29 (not via `manage.py makemigrations` — running any
# management command locally triggers AppConfig.ready(), which logs into the live
# Angel One session as a side effect). Matches the field exactly as edited in
# stocks/models.py's ShortTermSignal.Status.
#
# Audit remediation plan item 2.7: CANCELLED, CLOSED, and COOLDOWN were defined on
# ShortTermSignal.Status but never assigned anywhere in the codebase (confirmed via
# grep and a direct DB check — zero rows use any of these three values). CLOSED
# duplicated what ARCHIVED already covers (`_exit_signal()` in trade_engine.py always
# sets the terminal status to ARCHIVED, never CLOSED). CANCELLED duplicated what
# EXPIRED already covers (`run_expiry_cleanup()` transitions stale PENDING setups to
# EXPIRED, not CANCELLED). COOLDOWN was never referenced outside its own definition —
# cooldown tracking is already handled by the separate `cooldown_until` field on
# ARCHIVED rows. Metadata-only change: choices= narrowed, no data migration needed
# since no rows use the removed values.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0031_telegramlog_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorttermsignal',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('ACTIVE', 'Active'),
                    ('TARGET1', 'Target 1'),
                    ('TARGET2', 'Target 2'),
                    ('HIT_TARGET', 'Hit Target'),
                    ('HIT_SL', 'Hit SL'),
                    ('TRAILING_EXIT', 'Trailing Exit'),
                    ('TIME_STOP', 'Time Stop Exit'),
                    ('EXPIRED', 'Expired'),
                    ('REVIEW_REQUIRED', 'Review Required'),
                    ('ARCHIVED', 'Archived'),
                ],
                db_index=True,
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
