# Generated by hand 2026-07-29 (not via `manage.py makemigrations` — running any
# management command locally triggers AppConfig.ready(), which logs into the live
# Angel One session as a side effect). Matches stocks/models.py exactly as edited.
#
# Audit remediation plan item 3.4.2: dead `Trade` model. No admin registration, no
# serializer, no view or service ever wrote to `Trade.objects` (confirmed via grep
# across backend/ — the only reference besides the model definition itself was a
# dead `from stocks.models import (..., Trade, ...)` in trade_engine.py that was
# never instantiated; `db_trade` variables in that file are actually
# `ShortTermSignal` instances, unrelated to this model despite the name). The only
# live FK to it was `TelegramLog.trade`, which is never populated — every
# `TelegramLog.objects.create(...)` call site passes `short_term_signal=`, never
# `trade=`.
#
# NOTE: `TradeHistory` (db_table 'trade_history') is a completely different model —
# it FKs to `ShortTermSignal`, not this `Trade` model — and is untouched by this
# migration despite the naming collision.
#
# This migration removes the now-dead `trade` FK column from `telegram_logs` and
# drops the `trades` table entirely.
#
# CAUTION: `RemoveField`/`DeleteModel` below compile to `ALTER TABLE telegram_logs
# DROP COLUMN trade_id` and `DROP TABLE trades`. Both are destructive. A live
# `Trade.objects.count()` check against production has NOT been performed as part of
# this change (forbidden locally — running any `manage.py` command triggers a live
# Angel One login via `AppConfig.ready()`) — the account owner must confirm the
# `trades` table is actually empty in production before this migration is applied
# there.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0032_alter_shorttermsignal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramlog',
            name='trade',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
