# Generated by hand 2026-07-29 (not via `manage.py makemigrations` — running any
# management command locally triggers AppConfig.ready(), which logs into the live
# Angel One session as a side effect). Matches the constraint exactly as added to
# stocks/models.py's ShortTermSignal.Meta.
#
# Audit remediation plan item 3.1.4: ShortTermSignal had no DB-level uniqueness
# constraint, unlike SignalHistory.Meta ('unique_live_signal'). Dedup was only a
# scanner-wide cache lock (trade_engine.py, lock_key = "trade_engine_scanner_running")
# plus an unlocked `.exists()` check — two overlapping scanner runs (lock miss
# window, or a manual + scheduled run) could both pass `.exists()` before either
# inserted, producing duplicate live rows for the same symbol.
#
# Fix: a partial unique index on `symbol`, scoped to the non-terminal/live status
# values (PENDING, ACTIVE, TARGET1, TARGET2, REVIEW_REQUIRED) — the same status
# list `trade_engine.py`'s existing duplicate check already uses. Everything else
# (HIT_TARGET, HIT_SL, TRAILING_EXIT, TIME_STOP, EXPIRED, ARCHIVED) is terminal, so
# multiple historical rows per symbol in those states remain allowed.
#
# Depends on 0032_alter_shorttermsignal_status (Phase 2 #2.7), which already
# removed the dead CANCELLED/CLOSED/COOLDOWN choices from this same enum — this
# migration's condition list only references values that still exist post-0032.
#
# Renumbered from 0033 to 0034 (2026-07-29): 0033 was independently claimed by
# the dead-Trade-model-removal migration (Phase 3 #3.4.2), written by a parallel
# agent working on a different item. Depends on that migration instead of 0032
# directly, since it's now the actual latest migration in the chain.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0033_remove_dead_trade_model'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shorttermsignal',
            constraint=models.UniqueConstraint(
                condition=models.Q(('status__in', [
                    'PENDING', 'ACTIVE', 'TARGET1', 'TARGET2', 'REVIEW_REQUIRED',
                ])),
                fields=('symbol',),
                name='unique_live_short_term_signal',
            ),
        ),
    ]
