# Generated by hand 2026-07-29 (not via `manage.py makemigrations` — running any
# management command locally triggers AppConfig.ready(), which logs into the live
# Angel One session as a side effect).
#
# New table for SwingV2ShadowRun: one row per day the Swing V2 shadow scan
# (run_swing_v2_shadow, dry_run=True) actually executes. That job's own docstring
# says it "persists nothing" by design — no SignalCandidate rows — which left the
# ~20-session shadow-evidence gate for Phase 5 item A (doc/AUDIT_REMEDIATION_PLAN.md)
# with no durable way to count real sessions run so far. This table is separate
# from every live engine's read path, so it can't affect trading behavior.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0034_shorttermsignal_unique_live_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwingV2ShadowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(db_index=True, unique=True)),
                ('funnel', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'swing_v2_shadow_runs',
                'ordering': ['-run_date'],
            },
        ),
    ]
