# Generated by Django 4.2.30 on 2026-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0035_swingv2shadowrun'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signalhistory',
            index=models.Index(fields=['category', 'status', '-generated_at'], name='sh_cat_status_gen_idx'),
        ),
    ]
