# Generated by Django 4.2.29 on 2026-04-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
    ]
