# Generated by Django 4.2.29 on 2026-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_temporary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
