# Generated by Django 4.2.29 on 2026-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('gift_nifty_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('dow_jones_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('nasdaq_change', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('market_bias', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'global_market',
                'ordering': ['-date'],
            },
        ),
    ]
