# Generated by Django 4.2.29 on 2026-03-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmarket',
            name='dow_jones_ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='globalmarket',
            name='gift_nifty_ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='globalmarket',
            name='nasdaq_ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
