# Generated by Django 4.2.29 on 2026-03-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_market', '0002_globalmarket_dow_jones_ltp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmarket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
